os:
  - linux

language: node_js

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - npm install

deploy:
  provider: npm
  email: nicholas.brink@mattersight.com
  api_key: $NPM_TOKEN
  on:
    tags: true